feat: basic permission control
TexteaInc/y-socket.io pull request #13
Opened 2022-09-08 13:22 UTC by exuanbo

2022-09-08 19:47 UTC, Himself65 commented on src/types.ts
> +export type DefaultClientData = {}
make this into a `interface` and downstream could re-declare and extends it

2022-09-12 15:04 UTC, exuanbo commented
What do you think about this API design?

/cc @Himself65

2022-09-12 15:56 UTC, Himself65 requested changes

2022-09-12 15:56 UTC, Himself65 commented on src/server/socket/index.ts
> +      void room.destroy()
no void

2022-09-12 16:06 UTC, Himself65 requested changes

2022-09-12 17:45 UTC, Himself65 commented on .eslintrc.js
> -    'no-void': ['error', { allowAsStatement: true }]
I will move this to dev-kit later

2022-09-12 18:02 UTC, exuanbo commented on src/events.ts
> +  ['room:close']: () => void
This event is emitted in function `provider.closeRoom()` and it's not part of the sync protocol

2022-09-12 18:37 UTC, Himself65 approved these changes
There's a logic issue. 

If an owner closes a room, others could open it again with the same id and data. This caused the original owner to become a user. But we could fix it in the future.

2022-09-12 18:40 UTC, merged

2022-09-12 19:32 UTC, exuanbo commented
> There's a logic issue.
> 
> If an owner closes a room, others could open it again with the same id and data. This caused the original owner to become a user. But we could fix it in the future.

I've considered this issue. It will only happen when the server is created with option `autoDeleteRoom` (default to `false`).

I enabled this option in the example because it's easier to test.

https://github.com/TexteaInc/y-socket.io/blob/985dcd0909448b9ff45889f55c472eceb76d5613/example/scripts/server.ts#L15-L17

And currently the room data (`owner` etc.) is stored in memory by `roomMap`, in the future it will be better to provide a way to store the data in external database or something.